name: no_more_quotes
description: goomba

version: 3.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  audioplayers: 0.20.1
  dart_random_choice: 0.1.0-nullsafety.0
  share: 2.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  test: any
  mockito: 5.1.0
  flutter_launcher_icons: 0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/doakes.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/images/