name: Flutter CI
on:
  push:
    branches:
      - '*'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
    - run: flutter pub get
    - run: dart format --line-length 120 --set-exit-if-changed .
    - run: flutter analyze
    - run: flutter test
    - name: Integration tests
      uses: malinskiy/action-android/emulator-run-cmd@release/0.1.6
      with:
        cmd: flutter test integration_test
        api: 30
        abi: x86

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
      - run: flutter pub get
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: flutter build apk
